function plot_data( X1, Y1, X2, Y2, X3, Y3, axis_limits )

%PLOT_DATA(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 12-Mar-2017 18:35:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Vitórias de CPU 1','Marker','x','LineWidth',1.0,...
    'LineStyle','none',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);

% Create plot
plot(X2,Y2,'DisplayName','Vitórias de CPU 2','Marker','o','LineWidth',1.0,...
    'LineStyle','none',...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create plot
plot(X3,Y3,'DisplayName','Empates','Marker','^','LineWidth',1.0,'LineStyle','none',...
    'Color',[0 0.498039215803146 0]);

% Create xlabel
xlabel('Profundidade CPU 2');

% Create ylabel
ylabel('Profundidade CPU 1');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 axis_limits(1)]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 axis_limits(2)]);
box(axes1,'on');
% Create legend
hleg = legend(axes1,'show');
set(hleg,'Location','best')
legend('Vitórias de CPU 1', 'Vitórias de CPU 2', 'Empates');

end

